# Generated by Django 5.1.1 on 2024-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_coffee',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_milk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rewards_level',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
